keys:
  - &users
    - &rus age1mwsp9vznduxqxwsvva45htct25wartlsj707qyuz3fydt9tjnqdq5zfucs
  - &hosts
    - &desktop-wsl-01 age10sheugsj7txsnzv6j3yapstujrcde94ep9j82f3vtwx9z8aggfwsjtm9dm
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *rus
          - *desktop-wsl-01
